name: Build and Deploy Ludo Telegram Mini App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Check out the repository code
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up Java (required for Flutter)
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      # Set up Flutter
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.x' # Adjust to your Flutter version
          channel: 'stable'
          cache: true

      # Check if Flutter project exists, create if missing
      - name: Initialize Flutter project
        run: |
          if [ ! -f "pubspec.yaml" ]; then
            flutter create . --project-name=ludo_mini_app --platforms=web --no-overwrite
            echo "Created new Flutter project: ludo_mini_app"
          else
            echo "Flutter project already exists"
          fi

      # Install dependencies
      - name: Install dependencies
        run: flutter pub get

      # Add Telegram Web App package
      - name: Add Telegram Web App package
        run: flutter pub add telegram_web_app

      # Run tests (optional)
      - name: Run tests
        run: flutter test
        continue-on-error: true

      # Build the web app
      - name: Build web
        run: flutter build web --release --web-renderer canvaskit --base-href=/ludo_mini_app/
        # Matches GitHub Pages URL: https://<username>.github.io/ludo-mini-app/
